### PR TITLE
Adding extensible everything

### PR DESCRIPTION
**Pull request by jimmyhmiller**
Bigger than I thought, but the commits are smaller.

### CODE REVIEW

**Comment by ArchmageInc** [comment]
yay

**Comment by jimmyhmiller** [comment]
yay

**Comment by jimmyhmiller** [comment]
Because we said more than 50%, we need one more person correct?

**Comment by jimmyhmiller** [comment]
Because of  352, this can be merged.

**Comment by ArchmageInc** [comment]
The docker image has been tagged as archmageinc/nomic-bot:extensible. It has been deployed as archmageinc/nomic-bot:latest. The previous version was archmageinc/nomic-bot:fix103

**Pull request merged**
