### PR TITLE
331 - Population Growth

### PR DESCRIPTION
**Pull request by ArchmageInc**
For obvious reasons, we need a way for populations to expand. I am not married to this equation, but it is based on a standard growth model. It uses a base 1.1% growth with adjustments based on hunger / surplus where there is a sweet spot around having a surplus equal to 100% of demand.

### CODE REVIEW

**Comment by ArchmageInc** [comment]
yay

**Comment by rythompson** [comment]
yay

**Comment by dilbertKocik** [comment]
yay

**Comment by ArchmageInc** [comment]
Well that escalated quickly. I'll have to make some adjustments to Mr Nomic Bot to fix the 4200 points I now have.

**Pull request merged**
