### PR TITLE
354 - Have a Dog

### PR DESCRIPTION
**Pull request by jimmyhmiller**
Again I will create the command (and not fail at it) if this passes.

### CODE REVIEW

**Comment by jimmyhmiller** [comment]
yay

**Comment by dilbertKocik** [comment]
Haha, this is fantastic. Why only one dog though?

**Comment by dilbertKocik** [comment]
yay

**Comment by jimmyhmiller** [comment]
I have lots of plans for dogs and having multiple dogs would make them too hard to program.

**Comment by allensb** [comment]
yay

**Pull request merged**
