### PR TITLE
Mutate Rule 201

### PR DESCRIPTION
**Pull request by ArchmageInc**
This proposed change is designed to allow free-flow gameplay without forcing turn and order restrictions.

### CODE REVIEW

**Comment by nomicness** [comment]
You also are in violation of rule #108.

> 1. Each proposed rule-change shall be given a number for reference. The numbers shall begin with 301, and each rule-change proposed in the proper way shall receive the next successive integer, whether or not the proposal is adopted.

You should make that your title of your PR. This is Jimmy. (Wrong account sorry)

**Comment by ArchmageInc** [comment]
Ugh, so the idea of just adding to the rule set may make this cumbersome as keeping rule 201 and having 301 which modifies 201 will make this very difficult to read.

**Comment by ArchmageInc** [comment]
Okay. The PR has been updated.

**Comment by jimmyhmiller** [comment]
The way we did it is to delete the old law and to put the new law below. Order matters with these laws. So you shouldn't edit in place but delete and append.

**Comment by ArchmageInc** [comment]
So... delete 201 and add 301 in it's place?

**Comment by jimmyhmiller** [comment]
No, not in its place, at the end.

**Comment by jimmyhmiller** [comment]
But we can decide on that. Whatever you thinks works best. That's just how we did it before.

**Comment by ArchmageInc** [comment]
Okay. That'll work.

**Comment by ArchmageInc** [comment]
Good now?

**Comment by jimmyhmiller** [comment]
Looks great to me.

**Comment by ArchmageInc** [comment]
Is that a yay?

**Comment by jimmyhmiller** [comment]
You can open it up for a vote. Just leave a comment. Robert has officially joined (he forked).

**Comment by ArchmageInc** [comment]
I thought simply creating the PR was opening it to the vote?

**Comment by jimmyhmiller** [comment]
I guess that's true. We just can't start voting if you are going to make any more changes. Then the vote doesn't count.

**Comment by ArchmageInc** [comment]
Yeah, for now that's a blue line rule, but we will need to formalize it. Any changes after a vote is cast nullifies previous votes and those players must revote or something.

**Comment by jimmyhmiller** [comment]
Aye

**Comment by ArchmageInc** [comment]
Aye

**Comment by ArchmageInc** [comment]
I need to make a change.

**Comment by jimmyhmiller** [comment]
What change?

**Comment by ArchmageInc** [comment]
nevermind

**Comment by dilbertKocik** [comment]
Aye

**Pull request merged**
