### PR TITLE
347 - Synthetic Materials

### PR DESCRIPTION
**Pull request by ArchmageInc**
Chemicals are bad 'm 'k

### CODE REVIEW

**Comment by ArchmageInc** [comment]
yay

**Comment by dilbertKocik** [comment]
Do you want to give any kind of background on this? We can't make chemicals right now. So what are you going for here?

**Comment by ArchmageInc** [comment]
I am laying down ground work for the future. Since we still do not have a way to submit multiple rules at once, I am doing it in pieces.

**Comment by dilbertKocik** [comment]
Obviously, which is why I asked for background. What's the gameplan here? You're leading with a rule that potentially harms my population. So you're going to need to convince me to vote yay (if you care about my vote anyway).

**Comment by allensb** [comment]
yay

**Comment by ArchmageInc** [comment]
@dilbertKocik This is really just to introduce competing resources. While we have no real definitions for what synthetic is, it was also designed to spark involvement. The second goal of this cannot, at this time, be considered a success.

**Comment by dilbertKocik** [comment]
lulz

**Comment by jimmyhmiller** [comment]
yay

**Pull request merged**
