### PR TITLE
Vastly simplified happy.

### PR DESCRIPTION
**Pull request by jimmyhmiller**
I hated the way happy looked. It was so large and really got away from the essence of what it was supposed to do. Plus, I am going to have to implement `/train` and it is also a throttle command. In fact, I think throttled commands will become more common. So, I've abstracted the throttledCommand away. If you want to do a throttled command it becomes incredibly easy. Also, I hated that I had to think about undefined, NaN, and the range of a number when adding. So I made an add function that handles all of those cases for me.

This bot is some of the most fun I've had programming in a long time. Eliminating incidental complexity and allowing yourself the ability to only specify exactly what your problem requires is so satisfying.

### CODE REVIEW

**Comment by jimmyhmiller** [comment]
yay

**Comment by ArchmageInc** [comment]
Since this includes the /train command, I would rather wait for this to go in until the train rule change passes.

**Comment by jimmyhmiller** [comment]
Oh that is a mistake. I will fix that. It is also conflicted and needs fixing anyways

**Comment by jimmyhmiller** [comment]
In fact, that was the conflict. I including the import but not the file, which conflicted.

**Comment by ArchmageInc** [comment]
yay

**Comment by jimmyhmiller** [comment]
@allensb @dilbertKocik Mind voting on this?

**Comment by allensb** [comment]
Nice. Very clean.

**Comment by allensb** [comment]
yay

**Comment by ArchmageInc** [comment]
The docker image has been tagged as archmageinc/nomic-bot:simpleHappy. It has been deployed as archmageinc/nomic-bot:latest. The previous version was archmageinc/nomic-bot:dog

**Pull request merged**
