### PR TITLE
322 Partial War Reenactment

### PR DESCRIPTION
**Pull request by ArchmageInc**

### CODE REVIEW

**Comment by jimmyhmiller** [comment]
Shouldn't this be 323?

**Comment by ArchmageInc** [comment]
There was no 322

**Comment by ArchmageInc** [comment]
Yay

**Comment by rythompson** [comment]
Nay

**Comment by rythompson** [comment]
I already won the war

**Comment by ArchmageInc** [comment]
You didn't win any war!

**Comment by rythompson** [comment]
At the time, there were no rules. I declared victory. Therefore I won.

**Comment by dilbertKocik** [comment]
nay

**Comment by jimmyhmiller** [comment]
nay

**Pull request closed without merging**
