### PR TITLE
348 - Happiness in Villages

### PR DESCRIPTION
**Pull request by jimmyhmiller**
@ArchmageInc I actually did it!

### CODE REVIEW

**Comment by dilbertKocik** [comment]
I'm interested to see where this goes.

**Comment by ArchmageInc** [comment]
Me too. Open?

**Comment by dilbertKocik** [comment]
yay

**Comment by jimmyhmiller** [comment]
yay

**Comment by jimmyhmiller** [comment]
@ArchmageInc Mind voting on this? I'd love to get another proposal out.

**Comment by ArchmageInc** [comment]
Oh sure, now I'm the laggard

**Comment by ArchmageInc** [comment]
Yay

**Pull request merged**
