### PR TITLE
337 - immigration

### PR DESCRIPTION
**Pull request by dilbertKocik**
I have hungry people who I'm sure would prefer to move to a better place before they die. :)

### CODE REVIEW

**Comment by ArchmageInc** [comment]
You have the title of the PR right, but the ordinal of the law itself is off.

**Comment by dilbertKocik** [comment]
You're right. Thanks.

**Comment by dilbertKocik** [comment]
Yay

**Comment by ArchmageInc** [comment]
yay

**Comment by allensb** [comment]
Yay

**Pull request merged**
