### PR TITLE
321 - Cleaning up after war.

### PR DESCRIPTION
**Pull request by jimmyhmiller**

### CODE REVIEW

**Comment by ArchmageInc** [comment]
What? Why!?!

**Comment by dilbertKocik** [comment]
Why not?

**Comment by ArchmageInc** [comment]
Because. I fully intend for this to become a life long war. Wherein Ryans People and my People evolve into generations of hatred and have no idea why other than that is just how it has always been.

**Comment by jimmyhmiller** [comment]
I don't want open issues that are not actionable.

**Comment by ArchmageInc** [comment]
Then instead, make them actionable.

**Comment by jimmyhmiller** [comment]
I knew you would say that.

**Comment by ArchmageInc** [comment]
Please see #37 (322)

**Comment by jimmyhmiller** [comment]
Yay

**Comment by ArchmageInc** [comment]
Nay

**Comment by rythompson** [comment]
Nay

**Comment by ArchmageInc** [comment]
Quorum reached...

**Comment by dilbertKocik** [comment]
yay

**Comment by ArchmageInc** [comment]
50 / 50 what now?

**Comment by rythompson** [comment]
Doesn't matter I already won the war

**Comment by thematrimix** [comment]
Given that there is no longer an rules for war I would have to agree with this rule.

**Comment by thematrimix** [comment]
yay

**Comment by ArchmageInc** [comment]
@thematrimix type /roll 2d6+1 for your points.

**Comment by ArchmageInc** [comment]
I will add the points to your file @thematrimix

**Comment by ArchmageInc** [comment]
nay

**Comment by ArchmageInc** [comment]
nay

**Comment by ArchmageInc** [comment]
nay

**Comment by ArchmageInc** [comment]
nay

**Comment by ArchmageInc** [comment]
nay

**Comment by ArchmageInc** [comment]
nay

**Comment by ArchmageInc** [comment]
nay

**Comment by ArchmageInc** [comment]
nay

**Comment by ArchmageInc** [comment]
nay

**Comment by ArchmageInc** [comment]
nay

**Comment by ArchmageInc** [comment]
nay

**Comment by ArchmageInc** [comment]
This concludes our testing.

**Comment by ArchmageInc** [comment]
nay

**Comment by rythompson** [comment]
AHHHHHHHHHHHHH

**Comment by ArchmageInc** [comment]
Okay sorry. I'm done. The nomic-bot will now properly manage Quorum, passing, failing, and tied tags.

**Comment by ArchmageInc** [comment]
nay

**Comment by ArchmageInc** [comment]
nay

**Comment by ArchmageInc** [comment]
nay

**Comment by ArchmageInc** [comment]
nay

**Comment by jimmyhmiller** [comment]
World Peace!

**Pull request merged**
