### PR TITLE
Fixed NaN happiness and kept it legal

### PR DESCRIPTION
**Pull request by jimmyhmiller**

### CODE REVIEW

**Comment by ArchmageInc** [comment]
@jimmyhmiller Should we include fixing the current players file so allen's happiness is not NaN?

**Comment by jimmyhmiller** [comment]
I would like for him to delete his comment and run the command again

**Comment by ArchmageInc** [comment]
Okay

**Comment by ArchmageInc** [comment]
The docker image tag happy has been updated. It has been deployed as archmageinc/nomic-bot:latest. The previous version was archmageinc/nomic-bot:quorum

**Comment by allensb** [comment]
Done. I'm happy again. 👍

**Pull request merged**
