### PR TITLE
335 - Keep people from changing points

### PR DESCRIPTION
**Pull request by jimmyhmiller**
My goal is to have a clear rule to fix the shenanigans that occurred.

### CODE REVIEW

**Comment by allensb** [comment]
The rule should explain what happens in the case that a rule is not specified for a specific scenario.

**Comment by ArchmageInc** [comment]
Can this just be an amendment to the rule that says the same thing?

**Comment by jimmyhmiller** [comment]
Yay, I can do that.

**Comment by jimmyhmiller** [comment]
Meant to put yeah. I'll make a PR cause that shouldn't have counted as a
vote.

**Comment by ArchmageInc** [comment]
It wasn't counted

**Comment by ArchmageInc** [comment]
But, idk why it was even caught.

**Comment by jimmyhmiller** [comment]
If it had been opened it would have. It should only do it if that is the only text in the comment.

**Comment by jimmyhmiller** [comment]
@allensb If what you want to do is not a legal move, you can't do it. This has the consequence that we couldn't add a new player with points because there was no rule stating what to set their points to. That is just incentive for us to fix the rules.

**Comment by ArchmageInc** [comment]
yay, Nomic Bot has been fixed and should no longer parse non-votes which begin with yay, or end in nay

**Comment by allensb** [comment]
yay

**Comment by ArchmageInc** [comment]
Yay

**Comment by dilbertKocik** [comment]
yay

**Comment by jimmyhmiller** [comment]
yay

**Pull request merged**
