### PR TITLE
DECLARATION OF INACTIVITY

### PR DESCRIPTION
**Pull request by ArchmageInc**
It is hereby declared that @allensb, @jimmyhmiller, @dilbertKocik, @thematrimix, and @rythompson be considered inactive due to their... lack of activity.

In accordance with rule 110, this will remain for 1 business day and be accepted by >50% of active players less those being declared inactive. Currently, this would be 1 player... the one making the declaration... me. I will have a quorum all of you will be inactive, and I'll just sit here and play with myself.

> **110.** In order for a player to be active they must be on the active players list. Any player can make a proposal for another player(s) to be declared inactive. A player will be declared inactive if the following criteria have been met: (1) A majority of active players, minus the players who are being declared inactive, must accept the proposal, (2) a 24 hour business day must have passed from the time the proposal was created, (3) none of the players who are being declared inactive have performed any action since the proposal was created. The creator of the proposal may cancel their proposal at any time.

### CODE REVIEW

**Comment by ArchmageInc** [comment]
yay

**Comment by ArchmageInc** [comment]
Given that Monday is memorial day and the blue line laws use federal holidays as non-business days, The 1 business day will end on Tuesday May 31st 2016, at 5 pm Eastern Time.

**Comment by jimmyhmiller** [comment]
Hey Brandon. Sorry. We do need to play more. I have no excuses.

**Comment by dilbertKocik** [comment]
Ugh. Brandon still hasn't responded to my question on his PR. Plus I updated the players file. If anything I'm the most active player at this point. Not sure why you're lumping me in with the rest, Brandon. Not cool man. Not cool.

**Comment by ArchmageInc** [comment]
Because there has been activity from those being declared inactive, this declaration is now invalid.

**Pull request closed without merging**
