### PR TITLE
Update players.yaml

### PR DESCRIPTION
**Pull request by ArchmageInc**
I don't think I need a pull request for this, but I can't exactly remember and I'm driving so I can't go through and look at all the rules. I just want to make sure that you don't get the opportunity to pass any rule changes as you see fit. Also, Merry Christmas.

### CODE REVIEW

**Comment by jimmyhmiller** [comment]
nay

**Comment by ArchmageInc** [comment]
112. A player may add themselves to the active players list to become active. No individual may control more than one active player.

**Comment by jimmyhmiller** [comment]
Wow. How did I miss this? I should have made a new rule!!!

**Comment by ArchmageInc** [comment]
I really do appreciate the kindness of you sending the linked in message, because I didn't get the notification when you opened it, and you could have won the entire game.

**Comment by jimmyhmiller** [comment]
Just makes for a better story when I win for real :)

**Pull request merged**
