### PR TITLE
Implement dog

### PR DESCRIPTION
**Pull request by jimmyhmiller**

### CODE REVIEW

**Comment by jimmyhmiller** [comment]
yay

**Comment by ArchmageInc** [comment]
yay

**Comment by allensb** [comment]
yay

**Comment by ArchmageInc** [comment]
The docker image has been tagged as archmageinc/nomic-bot:dog. It has been deployed as archmageinc/nomic-bot:latest. The previous version was archmageinc/nomic-bot:happy

**Pull request merged**
