### PR TITLE
308 How to call a judgement

### PR DESCRIPTION
**Pull request by jimmyhmiller**

### CODE REVIEW

**Comment by dilbertKocik** [comment]
I'm not sure I understand what you mean when you say "move." I would have expected you to be talking about the legality of a given proposal but you go on to cover the "interpretation or application of a rule." I'm definitely being pedantic here because I understand the intention of this rule. But I do feel like this wording is ambiguous enough that you could call just about anything to judgement. Maybe that's what you're going for. But I can't tell.

**Comment by ArchmageInc** [comment]
nolo contendere

**Comment by jimmyhmiller** [comment]
I took the wording from the old rule but I do like the implications. For example, in our last game their was a disagreement on how points should be applied after the passing of a law. The law itself wasn't in question just how the points ought to be awarded after it passed. We needed a judgement and I want to make sure in scenarios like this (and many others) we could call one. So yes, I wanted it to be rather broad.

**Comment by jimmyhmiller** [comment]
Open for voting

**Comment by jimmyhmiller** [comment]
Yay

**Comment by jimmyhmiller** [comment]
Fixed merge conflict, no change to body of rule.

edit: twice

**Comment by dilbertKocik** [comment]
yay

**Comment by nomicness** [comment]
I was planning on merging this, but I do think we should let the original proposer be the one to merge or at least declare that it should be.

**Comment by jimmyhmiller** [comment]
I was planning on merging this, but I do think we should let the original proposer be the one to merge or at least declare that it should be.

**Comment by ArchmageInc** [comment]
Yes! ROBERT WAS IN VIOLATION OF THE RULES! The proposer is to resolve! (He did it so I wouldn't get the points)

**Pull request merged**
