### PR TITLE
Convert code to use es6 modules.

### PR DESCRIPTION
**Pull request by jimmyhmiller**
All of this was done mechanically using jscodeshift. I found a few codemods for it and wrote a simple one myself. The only thing that was done manually was in universe because I crossed the es6/commonjs boundry. In other words, this should all work. In the future I plan to start adding tests so we will have more confidence it all works.

### CODE REVIEW

**Comment by jimmyhmiller** [comment]
Click [here](https://github.com/nomicness/a-whole-new-world/pull/94/files?w=1) for a better view of what has changed. (hidden feature in github that ignores whitespace)

**Comment by jimmyhmiller** [comment]
Sorry for spamming you guys. This isn't right, working to fix it.

**Comment by jimmyhmiller** [comment]
Alright, finally it is call good. Sorry about the trouble.

**Comment by ArchmageInc** [comment]
@jimmyhmiller I do not have time to do a full review of all these changes. I must simply trust your skills.

**Comment by ArchmageInc** [comment]
The docker image has been pushed as latest and tagged as archmageinc/nomic-bot:redux. The container has been deployed. The previous version was archmageinc/nomic-bot:ohaul.

**Comment by jimmyhmiller** [comment]
Sorry about all the large PR's, I have one or two more and then everything should be reviewable.

**Pull request merged**
