### PR TITLE
349 - Repeal 105

### PR DESCRIPTION
**Pull request by jimmyhmiller**

### CODE REVIEW

**Comment by jimmyhmiller** [comment]
yay

**Comment by dilbertKocik** [comment]
Are we okay with taking out the part about allowing the creator to cancel their proposal which means it is not accepted? That technically means canceling a proposal doesn't have a defined process and that has gotten us into trouble before. I don't see that being an issue here but I just thought I should bring it up as a possible issue.

**Comment by dilbertKocik** [comment]
yay

**Comment by ArchmageInc** [comment]
yay

**Pull request merged**
