### PR TITLE
338 - Stop the killing!

### PR DESCRIPTION
**Pull request by jimmyhmiller**
This will prevent people from killing off their villages, but also just general stats editing.

### CODE REVIEW

**Comment by jimmyhmiller** [comment]
yay

**Comment by ArchmageInc** [comment]
Yay

**Comment by dilbertKocik** [comment]
nay

**Comment by thematrimix** [comment]
yay

**Comment by dilbertKocik** [comment]
So how are you defining "the rules" here? We have a loose concept that villages can have their own rules in addition to the laws we all abide by. But that isn't solidly fleshed out. If I went and made a file for my village to have my own rules is that going to be considered legitimate? Or do we have to flesh that out more first? And would this law only refer to the laws in this file or would it include an individual village's rules?

**Comment by jimmyhmiller** [comment]
@dilbert88 We need a law to clarify that.

**Pull request merged**
