### PR TITLE
319 Amendment of 315

### PR DESCRIPTION
**Pull request by ArchmageInc**
To prevent someone from the create, vote, remove loop...

### CODE REVIEW

**Comment by ArchmageInc** [comment]
yay

**Comment by dilbertKocik** [comment]
I'm confused. I thought we wanted to encourage voting in general. Why are we only incentivizing yay votes?

**Comment by ArchmageInc** [comment]
We're not. But the way the rule states now, I can create a proposal, vote, cancel the proposal, create another proposal, vote, cancel the proposal, create another proposal, vote, cancel the proposal....

**Comment by dilbertKocik** [comment]
Well that may be true but this still incentivizes yay votes. Would an acceptable compromise be something like quorum must be met in order for you to receive points? I suppose you could still create and cancel proposals but you would have to be a lot more organized to do it and anyone could join in if they're watching.

**Comment by ArchmageInc** [comment]
Compromise

**Comment by dilbertKocik** [comment]
yay

**Comment by rythompson** [comment]
yay

**Comment by ArchmageInc** [comment]
A quorum has been reached. Passing

**Pull request merged**
