### PR TITLE
318 - World Peace

### PR DESCRIPTION
**Pull request by jimmyhmiller**

### CODE REVIEW

**Comment by ArchmageInc** [comment]
How do you believe this would effect the currently in progress war?

**Comment by jimmyhmiller** [comment]
If this is approved before Monday, I think it would end it.

**Comment by jimmyhmiller** [comment]
I'm all in favor of having some sort of war games, but it should be opt in.

**Comment by ArchmageInc** [comment]
Opt in to war?

**Comment by jimmyhmiller** [comment]
That's why I called it a war game.

**Comment by ArchmageInc** [comment]
nay

**Comment by jimmyhmiller** [comment]
Yay

**Comment by dilbertKocik** [comment]
yay

**Comment by ArchmageInc** [comment]
I hate you all

**Pull request merged**
