### PR TITLE
355 - Train your dog

### PR DESCRIPTION
**Pull request by jimmyhmiller**
This one is more involved so I'm happy to hear feedback.

### CODE REVIEW

**Comment by ArchmageInc** [comment]
Do you want to open this?

**Comment by allensb** [comment]
So based on the odds there is a chance none of the events happen? But, it's stated that at least one event will happen. How will that be determined?

**Comment by ArchmageInc** [comment]
Allen makes a good point. Also, These should probably be split into two rules.

**Comment by jimmyhmiller** [comment]
There is not a chance that no event happens. The numbers and to 100 intentionally. If you want. Think about using that distribution to fill an array of 100 elements and picking one at random. I've done 100000 samples of it. It always returns an event.

**Comment by jimmyhmiller** [comment]
I don't like the idea of splitting this in to two laws.

**Comment by allensb** [comment]
I guess I fail to see how all the scenarios would return an event for a training value of 100.

Percentages are: 

Pee: 9
Cute: 77
Pic: 10.1

**Comment by jimmyhmiller** [comment]
You aren't doing your orders of operations correctly. I made them javascript functions so there wouldn't be any doubt about the values. Feel free to run them. Here is a table of all the values and their totals.

| training | pee | cute | pic | total |
| --- | --- | --- | --- | --- |
| 0 | 89 | 10 | 1 | 100 |
| 10 | 81 | 17 | 2 | 100 |
| 20 | 73 | 24 | 3 | 100 |
| 30 | 65 | 31 | 4 | 100 |
| 40 | 57 | 38 | 5 | 100 |
| 50 | 49 | 45 | 6 | 100 |
| 60 | 41 | 52 | 7 | 100 |
| 70 | 33 | 59 | 8 | 100 |
| 80 | 25 | 66 | 9 | 100 |
| 90 | 17 | 73 | 10 | 100 |
| 100 | 9 | 80 | 11 | 100 |

Here is the code I used to generate these values.

``` javascript
const dogPeesPercent = (training) => -0.80 * training + 89
const dogCutePercent = (training) => 0.7 * training + 10
const dogPicPercent = (training) => 0.1 * training + 1


_.range(0, 110, 10)
   .map(t => [t, dogPeesPercent(t), dogCutePercent(t), dogPicPercent(t), dogPeesPercent(t) + dogCutePercent(t) + dogPicPercent(t)])
   .map(row => row.join(","))
   .join("\n")
```

**Comment by allensb** [comment]
You are absolutely right. My bad!!!  :)

**Comment by allensb** [comment]
Strange. My elementary school just called and they want my elementary diploma back. This has been a rough start to this Monday.   haha

**Comment by jimmyhmiller** [comment]
yay

**Comment by ArchmageInc** [comment]
yay

**Comment by allensb** [comment]
yay

**Comment by jimmyhmiller** [comment]
I should have a PR later today for the command to be implemented. And hopefully a PR soon for the effect. My PR will depend on https://github.com/nomicness/a-whole-new-world/pull/124.

**Pull request merged**
