### PR TITLE
310 Remove negative incentive

### PR DESCRIPTION
**Pull request by jimmyhmiller**
I don't think we should have rules that incentive people to vote against proposals or to hold off their votes.

### CODE REVIEW

**Comment by ArchmageInc** [comment]
Ha ha ha

**Comment by ArchmageInc** [comment]
It is not simply a negative incentive. It is also a compensation for a rule being passed in which members may not have wanted passed.

**Comment by jimmyhmiller** [comment]
Yes, I understand that fact, but it is and will be used primarily as a way to get points when you know a law is already going to pass. Or as a reason to not vote on a law because you want the points. I am all for compensation for someone when a law passes they didn't want, if it doesn't have these negative consequences.

**Comment by ArchmageInc** [comment]
I do not disagree with you.

**Comment by jimmyhmiller** [comment]
Open for voting

**Comment by ArchmageInc** [comment]
Yay

**Comment by jimmyhmiller** [comment]
Yay

**Pull request merged**
