### PR TITLE
330 - Feed The People

### PR DESCRIPTION
**Pull request by ArchmageInc**
This rule governs Village Population's Hunger. The base idea is all hunger, farm production, and starvation calculations will occur once per week. The hunger branch of the nomic-bot is currently ready to automate hunger, farm production, and starvation. Purchasing farms (including SECTION 5) is still a manual process, but will soon be addressed. 

We can discuss the best day of the week for these calculations to happen.

### CODE REVIEW

**Comment by ArchmageInc** [comment]
FYI. The hunger branch changes to the nomic-bot now include the **/buy** command (having only a farm sub-command), which will abide by the rules as described in **330** It will deduct the farm cost, calculate production, reduce hunger, and modify the players.yaml file automatically.

**Comment by dilbertKocik** [comment]
yay

**Comment by ArchmageInc** [comment]
yay

**Comment by jimmyhmiller** [comment]
yay

**Comment by ArchmageInc** [comment]
Because the point calculator was not active when @dilbert88 and I voted, our points will be manually modified.

**Pull request merged**
