### PR TITLE
332 - Give the game some flavor

### PR DESCRIPTION
**Pull request by jimmyhmiller**

### CODE REVIEW

**Comment by jimmyhmiller** [comment]
@ArchmageInc Sorry it took so long. But I am going to start playing again.

**Comment by dilbertKocik** [comment]
I like this idea.

**Comment by ArchmageInc** [comment]
I like it, although @dilbert88 nor anyone other than Jimmy and I have created a village.

**Comment by dilbertKocik** [comment]
@ArchmageInc I would create a village but I don't know how to roll without creating an issue, or PR. If you joined the slack room you have been invited to you would know that. :)

**Comment by ArchmageInc** [comment]
wait what? What slack room?

**Comment by jimmyhmiller** [comment]
@ArchmageInc I sent you an invite in case you didn't have one already.

**Comment by dilbertKocik** [comment]
yay

**Comment by jimmyhmiller** [comment]
yay

**Comment by ArchmageInc** [comment]
yay

**Comment by allensb** [comment]
yay

**Pull request merged**
