### PR TITLE
Fix typo and change quorum to greater than 50%

### LINKED ISSUE #103: Nomic Bot Quorum
The Nomic Bot believes a quorum is reached with at least 50% of active members have voted instead of when more than 50% of active members have voted.

### PR DESCRIPTION
**Pull request by dilbertKocik**
Fixes #103.

### CODE REVIEW

**Comment by dilbertKocik** [comment]
yay

**Comment by ArchmageInc** [comment]
closes #103

**Comment by ArchmageInc** [comment]
yay

**Comment by ArchmageInc** [comment]
Since this is a bug fix, it is exempt from 350.

**Comment by dilbertKocik** [comment]
Oh, right. Good call.

**Comment by ArchmageInc** [comment]
The docker images has been tagged as archmageinc/nomic-bot:fix103. It has been deployed as archmageinc/nomic-bot:latest. The previous version was archmageinc/nomic-bot:buybug

**Pull request merged**
