### PR TITLE
32 (last + 1) amendment of 112

### PR DESCRIPTION
**Pull request by thematrimix**

### CODE REVIEW

**Comment by jimmyhmiller** [comment]
thematrimix - You aren't considered an active player because you aren't in the players.yaml.

**Comment by jimmyhmiller** [comment]
I would rather a change to the players.yaml be a separate PR. Any thoughts?

**Comment by ArchmageInc** [comment]
This should be 322, and players.yaml must be it's own PR. But we do welcome new players. Also, file changes should not include white space.

**Comment by jimmyhmiller** [comment]
@ArchmageInc Agree on both points.

**Comment by thematrimix** [comment]
Well about the separate PR for adding to active list. That is tricky because as soon as a play submits a rule then that player is active and not before. Thus, thus rule would create the dilemma such that no player may be active unless voted on and that defeats the purpose of the rule.

**Comment by ArchmageInc** [comment]
323 now that there is an official 322 proposal

**Comment by ArchmageInc** [comment]
I don't want to continually get nit picky, but this proposal is a rule violation. 

> **306.** PARSING PROPOSALS: A rule-change proposal must be submitted as a PR to the repository with a title which begins with only the numerical ordinal of the proposed rule. No other characters may preceed this number, and the number may not be written in word form.

**Comment by ArchmageInc** [comment]
Also, please separate your becoming active with an independent PR into players.yaml. 

> **112.** A player may add themselves to the active players list to become active. No individual may control more than one active player.

**Pull request closed without merging**
