### PR TITLE
317 No negative points

### PR DESCRIPTION
**Pull request by dilbertKocik**

### CODE REVIEW

**Comment by ArchmageInc** [comment]
I see your point involving 310

**Comment by dilbertKocik** [comment]
I'm actually taking out the precedence because, after speaking with Jimmy, I don't think it's necessary. If those rules explicitly stated that you could go negative then it would be necessary. But as the rules are right now, I don't think it is.

**Comment by jimmyhmiller** [comment]
Yay

**Comment by ArchmageInc** [comment]
yay

**Comment by rythompson** [comment]
yay

**Comment by rythompson** [comment]
Quorum reached. Merge at your leisure

**Pull request merged**
