### PR TITLE
334 - Initial Player Points

### PR DESCRIPTION
**Pull request by ArchmageInc**
Provided this rule passes, I will recall the currently open Call to Judgement under the common knowledge that the current Call to Judgement system is very broken. 

Also, Someone smarter than me please  fix the Call to Judgement system.

### CODE REVIEW

**Comment by dilbertKocik** [comment]
I don't have a problem with this. But just to be clear this rule doesn't address Allen at all since he is already a player.

**Comment by dilbertKocik** [comment]
Yay

**Comment by ArchmageInc** [comment]
I agree. Not that you are wrong about Allen violating the rules, but that this rule does not technically affect his circumstance of being misled by a supposed trusted member of the council. 

> **107.** No rule-change may take effect earlier than the moment of the completion of the vote that adopted it, even if its wording explicitly states otherwise. No rule-change may have retroactive application.

**Comment by ArchmageInc** [comment]
yay

**Comment by allensb** [comment]
I think that my introduction to this game, involving a violation of a rule, is really a great precursor for things to come!

**Comment by allensb** [comment]
yay

**Comment by jimmyhmiller** [comment]
I think this rule is ambiguous as stated.

**Comment by jimmyhmiller** [comment]
nay

**Comment by ArchmageInc** [comment]
Jimmy, please explain

**Comment by ArchmageInc** [comment]
Oh crap. I didn't mean to merge the change to the bot here. I meant to push that to master.

**Comment by ArchmageInc** [comment]
I think everyone has the same understanding. And even though incentive values are also awarded for failed proposals (the bot doesn't do this BTW) this law states the value for the last accepted proposal.

**Pull request merged**
