### PR TITLE
336 - Follow the Food

### PR DESCRIPTION
**Pull request by ArchmageInc**
This law is an attempt to save any villagers who may feel undervalued by their overseer.

### CODE REVIEW

**Comment by ArchmageInc** [comment]
yay

**Comment by dilbertKocik** [comment]
This is an interesting solution but I believe that other villages should be allowed to deny movement. Plus, they should be allowed to move for more reasons than simply hunger. In short, I prefer my proposal. Haha

**Comment by dilbertKocik** [comment]
nay

**Comment by ArchmageInc** [comment]
They could both be in effect I believe and should one not want said migrated population, let them starve and migrate again.

**Comment by jimmyhmiller** [comment]
WE NEED TO BUILD A WALL!! MAKE CREDO GREAT AGAIN!

**Comment by jimmyhmiller** [comment]
nay

**Comment by ArchmageInc** [comment]
Seriously you guys?

**Comment by ArchmageInc** [comment]
You all loset your minds when war is proposed, but saving lives is out of the question?

**Comment by jimmyhmiller** [comment]
yay

**Comment by allensb** [comment]
nay

**Comment by allensb** [comment]
I want the ability to deny entrance to my village.

**Pull request closed without merging**
