### PR TITLE
318 Vote on lower ordinal first

### PR DESCRIPTION
**Pull request by ArchmageInc**
The purpose of this rule is to engage voting on all active proposals.

### CODE REVIEW

**Comment by jimmyhmiller** [comment]
Test

**Comment by dilbertKocik** [comment]
yay

**Comment by ArchmageInc** [comment]
yay

**Comment by rythompson** [comment]
yay

**Comment by rythompson** [comment]
roll 2d6+1

**Comment by ArchmageInc** [comment]
Quorum reached, passing

**Pull request merged**
