### PR TITLE
353 - Make Em Happy

### PR DESCRIPTION
**Pull request by jimmyhmiller**
I will finish the bot changes if this is approved.

### CODE REVIEW

**Comment by jimmyhmiller** [comment]
yay

**Comment by ArchmageInc** [comment]
yay

**Comment by allensb** [comment]
yay

**Comment by jimmyhmiller** [comment]
@ArchmageInc Hasn't quorum been reached? We have 5 active players and three have voted. Can you check the logs? I'm sure if it is broken, it is my fault and I will fix it.

**Comment by dilbertKocik** [comment]
yay

**Pull request merged**
