### PR TITLE
310 Allow points to be exchanged

### PR DESCRIPTION
**Pull request by dilbertKocik**
Allow points to be exchanged. The purpose of this rule is to allow bartering to occur. We can create things to barter with later but we need a base rule to allow us to barter.

### CODE REVIEW

**Comment by dilbertKocik** [comment]
Something I find interesting about this rule is it sort of assumes we are setting up a society where scarcity is a thing. This works out well for me personally because I would like to explore the possibilities of moving to a post scarcity society later on and what sort of impacts that would have on a society with scarcity.

**Comment by nomicness** [comment]
Yay

**Comment by jimmyhmiller** [comment]
Yay

**Comment by ArchmageInc** [comment]
yay

**Comment by dilbertKocik** [comment]
yay

**Pull request merged**
