### PR TITLE
Declare players inactive

### PR DESCRIPTION
**Pull request by jimmyhmiller**

### CODE REVIEW

**Comment by jimmyhmiller** [comment]
yay

**Comment by nomicbot2** [comment]
@ArchmageInc We are the only two active players now. It seems like the bot is half running. Doesn't seem to respond to comments, but still runs updates. I can take over hosting if you don't want to fix it.

**Comment by ArchmageInc** [comment]
Yeah, I forgot all about the bot running. I haven't checked the logs in a long time. If you want to host it, I'll shut the other one down.

**Comment by jimmyhmiller** [comment]
Yeah, I can host things. My hope is to do it for free though, so I may have to find some other ways of making the recurring events occur. But now, we can propose any laws and as long as both of us agree they will pass. (Oh and accidentally commented as my new nomicbot account, sorry about that)

**Pull request merged**
