### PR TITLE
315 VOTING INCENTIVE

### PR DESCRIPTION
**Pull request by ArchmageInc**
Incentive for players to vote on proposals.

### CODE REVIEW

**Comment by jimmyhmiller** [comment]
Seems like a very weak incentive.

**Comment by ArchmageInc** [comment]
True, but at least it is something. I don't want to introduce too much inflation.

**Comment by dilbertKocik** [comment]
Inflation is a given though. In general, it's a bad idea to introduce a rule with a flat point value on it. I think it would be nicer if it were some kind of percentage of the total points the proposer will get if the proposal passes.

**Comment by ArchmageInc** [comment]
voting is very low effort and consistent. This keeps it simple and yes, it is only a small encouragement, but constant.

**Comment by ArchmageInc** [comment]
yay

**Comment by ArchmageInc** [comment]
There, I have increased the incentive a bit.

**Comment by rythompson** [comment]
yay

**Comment by ArchmageInc** [comment]
yay

**Comment by jimmyhmiller** [comment]
Yay

**Comment by ArchmageInc** [comment]
A quorum has been reached. The roll was just to verify the bot was still active and working, I assume points will only be awarded on future proposals.

**Pull request merged**
