### PR TITLE
343 - Spacetime

### PR DESCRIPTION
**Pull request by ArchmageInc**
Those who reside in the village of spaceport might find this interesting.

### CODE REVIEW

**Comment by jimmyhmiller** [comment]
Any particular motivation for this?

**Comment by ArchmageInc** [comment]
I don't like having no rule changes in progress, and it could be needed to make sure that everything we define exists in the same reality construct.

**Comment by allensb** [comment]
This rule is fine for now. Until proven otherwise. You really don't want us creating wormholes.  :)

**Comment by ArchmageInc** [comment]
Yay

**Comment by ArchmageInc** [comment]
Fuxk

**Comment by allensb** [comment]
yay

**Comment by allensb** [comment]
Still not open? Who wrote this bot?  jk  :)

**Comment by ArchmageInc** [comment]
Turns out it was invalid YAML in the players.yaml file. Thanks @dilbert88

**Comment by ArchmageInc** [comment]
yay

**Comment by allensb** [comment]
yay

**Comment by dilbertKocik** [comment]
yay

**Comment by dilbertKocik** [comment]
My bad on the players file. Sorry about that.

**Pull request closed without merging**
