### PR TITLE
309 OF WAR AND SPOILS

### PR DESCRIPTION
**Pull request by ArchmageInc**
The purpose of this rule is to govern WAR!!

### CODE REVIEW

**Comment by jimmyhmiller** [comment]
This seems rather hard to perform over the internet.

**Comment by ArchmageInc** [comment]
Because of the dice?

**Comment by jimmyhmiller** [comment]
I'm sure there are websites that could allow you to do it, but the coordination sounds difficult and agreement on what site would also make it challenging.

**Comment by ArchmageInc** [comment]
I think, as long as we are able to be honest about what we roll, it should not be a problem.

**Comment by jimmyhmiller** [comment]
I just don't know how you can be. I've been trying to think about a way to do random numbers where people can trust each other. I'm sure there is a way. But I think with a distributed game we will have to be a bit more complex than dice roll.

**Comment by ArchmageInc** [comment]
We can pass a future rule which will allow random number generators to be used wherever dice rolls are referenced.

**Comment by jimmyhmiller** [comment]
How do you get two parties in different rooms to agree on a random number generator and communicate what number it produced with complete trust? I am asking sincerely cause I have a proposal where I'd like randomness too, but don't know how to do it.

**Comment by ArchmageInc** [comment]
Pass a rule which states which to use.

**Comment by ArchmageInc** [comment]
Or write one and declare it is to be the one used. I would recommend it be open source...

**Comment by jimmyhmiller** [comment]
I promise I'm not trying to be nitpicky. I just feel like I'm misunderstanding, because if you have this solved I'm excited that I can implement my own rule as well. All the random number generators I know of are used to a single person. I go to a website or run a command and a number is generated.

If there are two players over the internet doing this, how does the other person verify that his opponent didn't cheat? He could have just said he generated it or just kept generating over and over again until he got the number he wanted.

**Comment by ArchmageInc** [comment]
I am not saying I have this solved. All I am saying is that for now, we are honorable people and can probably get by with it until we solve the problem. I completely understand your concern, but it is a problem which will have to be addressed, and this pushes the issue.

**Comment by ArchmageInc** [comment]
I am going to think on this before I open it to voting.

**Comment by ArchmageInc** [comment]
Okay, here's my thought: a Web application in which someone authenticates via GitHub Oauth, Enters the PR / Issue / Whatever on which the roll should be posted, enters the number and sides of the dice to be rolled. It randomly generates the numbers and posts them to the PR / Issue / Whatever as comment with its own credentials identifying who submitted the request and the results. 

Would that suffice?

**Comment by ArchmageInc** [comment]
I have a better thought.

**Comment by jimmyhmiller** [comment]
I came up and wrote this awesome bot by myself.

**Comment by ArchmageInc** [comment]
yay

**Comment by rythompson** [comment]
Yay

**Comment by ArchmageInc** [comment]
Quorum reached. Passing

**Pull request merged**
