### PR TITLE
333 - Naming the planet

### PR DESCRIPTION
**Pull request by jimmyhmiller**
If you could please leave comments give suggestions for names that would be helpful. We can give +1's to names we like and decide together on this.

### CODE REVIEW

**Comment by jimmyhmiller** [comment]
Veelox

**Comment by dilbertKocik** [comment]
Credo

**Comment by ArchmageInc** [comment]
Faerûn

**Comment by allensb** [comment]
Takodia

**Comment by ArchmageInc** [comment]
Scyludufyaax

**Comment by dilbertKocik** [comment]
yay

**Comment by allensb** [comment]
yay

**Comment by jimmyhmiller** [comment]
yay

**Comment by dilbertKocik** [comment]
yay

**Comment by jimmyhmiller** [comment]
yay

**Comment by allensb** [comment]
yay

**Comment by ArchmageInc** [comment]
Yay

**Pull request merged**
