### PR TITLE
325 - COUNTING VOTES

### PR DESCRIPTION
**Pull request by ArchmageInc**

### CODE REVIEW

**Comment by jimmyhmiller** [comment]
335?

**Comment by ArchmageInc** [comment]
My bad

**Comment by dilbertKocik** [comment]
Are we really going to make an explicit rule for absolutely everything that is implicit?

**Comment by dilbertKocik** [comment]
nay

**Comment by ArchmageInc** [comment]
yay

**Comment by ArchmageInc** [comment]
yay

**Comment by ArchmageInc** [comment]
yay

**Comment by ArchmageInc** [comment]
yay

**Comment by ArchmageInc** [comment]
yay

**Comment by ArchmageInc** [comment]
yay

**Comment by ArchmageInc** [comment]
yay

**Comment by ArchmageInc** [comment]
yay

**Comment by ArchmageInc** [comment]
yay

**Comment by ArchmageInc** [comment]
yay

**Comment by ArchmageInc** [comment]
yay

**Comment by ArchmageInc** [comment]
yay

**Comment by ArchmageInc** [comment]
yay

**Comment by ArchmageInc** [comment]
yay

**Comment by ArchmageInc** [comment]
yay

**Comment by ArchmageInc** [comment]
yay

**Comment by ArchmageInc** [comment]
yay

**Comment by ArchmageInc** [comment]
yay

**Comment by ArchmageInc** [comment]
yay

**Comment by ArchmageInc** [comment]
yay

**Comment by ArchmageInc** [comment]
yay

**Comment by thematrimix** [comment]
At current state I would vote nay. However, given that if a rule upon reaching a quorum does not have a majority (aka a tie) the then rule shall remain open for X biz days (where X is up to the rule creator). Upon, reaching X biz days it the vote is still not a majority it is closed (not rejected or accepted). This keeps stalled rules from hanging around. Also, that the rule can be brought back for a vote agains as there is no rule against it.

**Comment by thematrimix** [comment]
nay

**Comment by jimmyhmiller** [comment]
yay

**Comment by jimmyhmiller** [comment]
@dilbert88 This is not even implicit in the rules and needs to be spelled out.

**Comment by rythompson** [comment]
yay

**Comment by dilbertKocik** [comment]
I have been convinced I am a dum dum.

**Comment by dilbertKocik** [comment]
yay

**Comment by ArchmageInc** [comment]
yay

**Comment by ArchmageInc** [comment]
yay

**Comment by ArchmageInc** [comment]
yay

**Comment by ArchmageInc** [comment]
yay

**Comment by ArchmageInc** [comment]
yay

**Comment by ArchmageInc** [comment]
yay

**Pull request merged**
