### PR TITLE
345 - Sawmills

### PR DESCRIPTION
**Pull request by ArchmageInc**
This will introduce a new resource, lumber.

### CODE REVIEW

**Comment by ArchmageInc** [comment]
yay

**Comment by rythompson** [comment]
nay. I don't believe in wood

**Comment by rythompson** [comment]
nay

**Comment by rythompson** [comment]
fuck the rules

**Comment by rythompson** [comment]
burn it to the ground!

**Comment by ArchmageInc** [comment]
You're an ass

**Comment by allensb** [comment]
yay

**Pull request merged**
