### PR TITLE
340 - Surplus Exchange

### PR DESCRIPTION
**Pull request by ArchmageInc**
This is to introduce a bartering mechanic for food.

### CODE REVIEW

**Comment by ArchmageInc** [comment]
yay

**Comment by jimmyhmiller** [comment]
You call it surplus "echange" instead of exchange.

**Comment by dilbertKocik** [comment]
Lol gotta love Brandon's spelling. He got it right in the body.

**Comment by dilbertKocik** [comment]
But he called it "suplus" in the body. Where's the consistency?!

**Comment by dilbertKocik** [comment]
Yay

**Comment by allensb** [comment]
Yay

**Comment by allensb** [comment]
Thanks for making this law Brandon.

**Pull request merged**
