### PR TITLE
327 Village Institutions

### PR DESCRIPTION
**Pull request by ArchmageInc**
This is designed to begin a construct for future, purposeful gameplay. As we progress, I envision villages growing into towns, cities, metropolis, countries, planets, etc... Which must gather resources and grow in population and productivity. The "reset" clause is designed to provide incentive to ensure the safety and prosperity of the people.

### CODE REVIEW

**Comment by ArchmageInc** [comment]
Because this is somewhat substantial, I want to have a discussion around how to govern a construct which is governed by sections.

**Comment by jimmyhmiller** [comment]
Yay

**Comment by ArchmageInc** [comment]
yay

**Comment by dilbertKocik** [comment]
yay

**Pull request merged**
