### PR TITLE
Made adding a command simpler.

### PR DESCRIPTION
**Pull request by jimmyhmiller**
The whole idea here is that commands will be able to live in their own file. You can use the addCommand function to register your command. The only other thing you have to do is import your command in the index.

I'm thinking about doing similar things for the interpreter and building the world.

### CODE REVIEW

**Comment by jimmyhmiller** [comment]
Look a PR that isn't crazy!

**Comment by dilbertKocik** [comment]
This is really neat. It makes the bot a lot more approachable since you don't have to touch a lot of files that you may be unfamiliar with.

**Comment by jimmyhmiller** [comment]
@ArchmageInc Any opposition to merging this?

**Comment by jimmyhmiller** [comment]
Going to try using the voting commands for this to see if they work here. Don't expect them to.

**Comment by jimmyhmiller** [comment]
yay

**Comment by jimmyhmiller** [comment]
Okay, open does, but tallying doesn't. I will work on that later.

**Comment by ArchmageInc** [comment]
@jimmyhmiller Sorry, I was in the mountains enjoying not having 90%+ humidity.

**Comment by ArchmageInc** [comment]
I am going to merge this as it was in place before 350

**Comment by ArchmageInc** [comment]
The docker images has been tagged as archmageinc/nomic-bot:simplecommands. It has been deployed as archmageinc/nomic-bot:latest. The previous version was archmageinc/nomic-bot:namedexports

**Pull request merged**
