### PR TITLE
Moved open to new command style. 

### PR DESCRIPTION
**Pull request by jimmyhmiller**
This was mostly a test to see what it would take. I actually think it was fairly simple. Even though I had to add things to the world, and add a new command, nothing was difficult about the translation. As time goes on, I will translate more commands over to the new architecture.

One thing I didn't handle in my translation is a proper message for inactivePlayers. That is because I plan on implementing some sort of validation functionality soon. That way those sorts of concerns can be dealt with across commands.

### CODE REVIEW

**Comment by ArchmageInc** [comment]
Jesus I can't deploy this shit fast enough, let alone review these changes.

**Comment by ArchmageInc** [comment]
@dilbertKocik You pass this one?

**Comment by jimmyhmiller** [comment]
If you want me to take over hosting I can. Or we can automate the deploy.

**Comment by dilbertKocik** [comment]
Yeah, looks good to me.

**Comment by dilbertKocik** [comment]
yay

**Comment by dilbertKocik** [comment]
Point of clarification: I gave a thumbs up for automating the deploy.

**Comment by ArchmageInc** [comment]
I agree and I do intend to automate it. Right now I have it set up on a script that is mostly automated

**Comment by jimmyhmiller** [comment]
yay

**Comment by ArchmageInc** [comment]
This is clear for go yes?

**Comment by jimmyhmiller** [comment]
Yes it is.

**Comment by ArchmageInc** [comment]
The docker image has been tagged as archmageinc/nomic-bot:newopen. It has been deployed as archmageinc/nomic-bot:latest. The previous version was archmageinc/nomic-bot:extensible

**Pull request merged**
